<a href="https://colab.research.google.com/github/WoradeeKongthong/raining_tomorrow_classification/blob/master/02_Raining_LogisticEngineering_plus_FeatureEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# libraries
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# **Data Set**

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/WoradeeKongthong/raining_tomorrow_classification/master/weatherAUS.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           142193 non-null  object 
 1   Location       142193 non-null  object 
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  object 
 8   WindGustSpeed  132923 non-null  float64
 9   WindDir9am     132180 non-null  object 
 10  WindDir3pm     138415 non-null  object 
 11  WindSpeed9am   140845 non-null  float64
 12  WindSpeed3pm   139563 non-null  float64
 13  Humidity9am    140419 non-null  float64
 14  Humidity3pm    138583 non-null  float64
 15  Pressure9am    128179 non-null  float64
 16  Pressure3pm    128212 non-null  float64
 17  Cloud9am       88536 non-null

In [0]:
# drop RISK_MM column (Recommendation from data description in Kaggle)
df.drop(['RISK_MM'], axis = 1, inplace = True)

# Extract Year, Month, Day from Date column
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

# drop Date column
df.drop(['Date'], axis = 1, inplace = True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Location       142193 non-null  object 
 1   MinTemp        141556 non-null  float64
 2   MaxTemp        141871 non-null  float64
 3   Rainfall       140787 non-null  float64
 4   Evaporation    81350 non-null   float64
 5   Sunshine       74377 non-null   float64
 6   WindGustDir    132863 non-null  object 
 7   WindGustSpeed  132923 non-null  float64
 8   WindDir9am     132180 non-null  object 
 9   WindDir3pm     138415 non-null  object 
 10  WindSpeed9am   140845 non-null  float64
 11  WindSpeed3pm   139563 non-null  float64
 12  Humidity9am    140419 non-null  float64
 13  Humidity3pm    138583 non-null  float64
 14  Pressure9am    128179 non-null  float64
 15  Pressure3pm    128212 non-null  float64
 16  Cloud9am       88536 non-null   float64
 17  Cloud3pm       85099 non-null

In [0]:
X = df.drop(['RainTomorrow'], axis=1)
y = df['RainTomorrow']

# **Trial 1**
- keep the outliers
- impute the missing categorical values with mode
- impute the missing numerical values with median

**Create Preprocessor : ColumnTransformer of numerical and categorical features**

In [0]:
numerical_features = [x for x in X.columns if df[x].dtype != 'object']

numeric_transformer = Pipeline(steps=[
          ('imputer', SimpleImputer(strategy='median')),
          ('scaler', MinMaxScaler())
])

categorical_features = [x for x in X.columns if df[x].dtype == 'object']

categorical_transformer = Pipeline(steps=[
          ('imputer', SimpleImputer(strategy='most_frequent')),
          ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
          ('num', numeric_transformer, numerical_features),
          ('cat', categorical_transformer, categorical_features)
    ]
)

**Create model**

In [0]:
model = LogisticRegression(solver='sag', max_iter=500, n_jobs = -1)

**Create Pipeline**

In [0]:
clf = Pipeline(steps=[
      ('preprocessor', preprocessor),
      ('model', model)
])

**Cross Validation**

In [10]:
accuracy = cross_val_score(clf,X,y,cv=10)
print('accuracy : ', accuracy)
print('mean : ', accuracy.mean())
print('std : ', accuracy.std())

accuracy :  [0.8326301  0.68994374 0.83410689 0.71158309 0.81559885 0.5278149
 0.67156621 0.6257824  0.71763134 0.83409522]
mean :  0.7260752747680471
std :  0.09830128530393102


Note : It looks like the model has not high bias and variance

**Training and Test Sets**

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('\n\nTraining and Test Sets result')
print('\naccuracy score : ', accuracy_score(y_test,y_pred))
print('\nconfusion matrix : \n', confusion_matrix(y_test, y_pred))
print('\nclassification report : \n', classification_report(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)




Training and Test Sets result

accuracy score :  0.8447554414712191

confusion matrix : 
 [[20840  1191]
 [ 3224  3184]]

classification report : 
               precision    recall  f1-score   support

           0       0.87      0.95      0.90     22031
           1       0.73      0.50      0.59      6408

    accuracy                           0.84     28439
   macro avg       0.80      0.72      0.75     28439
weighted avg       0.83      0.84      0.83     28439



In [12]:
print('Training set score : ',clf.score(X_train,y_train))
print('Test set score : ',clf.score(X_test,y_test))

Training set score :  0.8489283893313642
Test set score :  0.8447554414712191


Note : The model is not overfitting

# Trial 2 
- drop the outliers from df
- impute the missing categorical values with mode
- impute the missing numerical values with median

In [29]:
# dropping the outliers

Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df_drop_outliers = df[~((df < (Q1 - 1.5*IQR)) | (df > (Q3 + 1.5*IQR))).any(axis=1)]
df_drop_outliers

Location  MinTemp  MaxTemp  Rainfall  ...  RainTomorrow  Year Month  Day
0        Albury     13.4     22.9       0.6  ...            No  2008    12    1
1        Albury      7.4     25.1       0.0  ...            No  2008    12    2
2        Albury     12.9     25.7       0.0  ...            No  2008    12    3
3        Albury      9.2     28.0       0.0  ...            No  2008    12    4
4        Albury     17.5     32.3       1.0  ...            No  2008    12    5
...         ...      ...      ...       ...  ...           ...   ...   ...  ...
142188    Uluru      3.5     21.8       0.0  ...            No  2017     6   20
142189    Uluru      2.8     23.4       0.0  ...            No  2017     6   21
142190    Uluru      3.6     25.3       0.0  ...            No  2017     6   22
142191    Uluru      5.4     26.9       0.0  ...            No  2017     6   23
142192    Uluru      7.8     27.0       0.0  ...            No  2017     6   24

[109459 rows x 25 columns]

In [0]:
X = df_drop_outliers.drop(['RainTomorrow'], axis=1)
y = df_drop_outliers['RainTomorrow']

**Cross Validation**

In [31]:
accuracy = cross_val_score(clf,X,y,cv=10)
print('accuracy : ', accuracy)
print('mean : ', accuracy.mean())
print('std : ', accuracy.std())

accuracy :  [0.86424265 0.76247031 0.85236616 0.78722821 0.86113649 0.72300384
 0.70847798 0.6459894  0.74666545 0.86477844]
mean :  0.781635892366505
std :  0.07339684435367744


Note : Dropping the outliers improves the model

**Training and Test Sets**

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('\n\nTraining and Test Sets result')
print('\naccuracy score : ', accuracy_score(y_test,y_pred))
print('\nconfusion matrix : \n', confusion_matrix(y_test, y_pred))
print('\nclassification report : \n', classification_report(y_test,y_pred))



Training and Test Sets result

accuracy score :  0.8726932212680432

confusion matrix : 
 [[17800   568]
 [ 2219  1305]]

classification report : 
               precision    recall  f1-score   support

           0       0.89      0.97      0.93     18368
           1       0.70      0.37      0.48      3524

    accuracy                           0.87     21892
   macro avg       0.79      0.67      0.71     21892
weighted avg       0.86      0.87      0.86     21892



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [16]:
print('Training set score : ',clf.score(X_train,y_train))
print('Test set score : ',clf.score(X_test,y_test))

Training set score :  0.8719494786848927
Test set score :  0.8726932212680432


Note : The model is not overfitting

# Trial 3
- drop the outliers from X_train
- impute the missing categorical values with mode
- impute the missing numerical values with median

In [17]:
df

Location  MinTemp  MaxTemp  Rainfall  ...  RainTomorrow  Year Month  Day
0        Albury     13.4     22.9       0.6  ...            No  2008    12    1
1        Albury      7.4     25.1       0.0  ...            No  2008    12    2
2        Albury     12.9     25.7       0.0  ...            No  2008    12    3
3        Albury      9.2     28.0       0.0  ...            No  2008    12    4
4        Albury     17.5     32.3       1.0  ...            No  2008    12    5
...         ...      ...      ...       ...  ...           ...   ...   ...  ...
142188    Uluru      3.5     21.8       0.0  ...            No  2017     6   20
142189    Uluru      2.8     23.4       0.0  ...            No  2017     6   21
142190    Uluru      3.6     25.3       0.0  ...            No  2017     6   22
142191    Uluru      5.4     26.9       0.0  ...            No  2017     6   23
142192    Uluru      7.8     27.0       0.0  ...            No  2017     6   24

[142193 rows x 25 columns]

In [0]:
X = df.drop(['RainTomorrow'], axis=1)
y = df['RainTomorrow']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [49]:
X_train

Location  MinTemp  MaxTemp  ...  Year  Month  Day
89080          GoldCoast     18.3     19.8  ...  2012      5   25
56495           Ballarat      7.6     25.1  ...  2016     12    1
63581   MelbourneAirport      7.7     13.4  ...  2011      5   26
21452      NorfolkIsland     15.5     20.3  ...  2011      5   16
2498              Albury     18.1     32.8  ...  2016      1   25
...                  ...      ...      ...  ...   ...    ...  ...
17553          Newcastle     25.1     40.7  ...  2017      1   31
38527         WaggaWagga      8.8     16.0  ...  2016      8   10
131812        Launceston      4.4     14.5  ...  2014      7    7
1510              Albury      1.7     20.6  ...  2013      5    3
119227             Perth      3.8     17.1  ...  2012      9   28

[113754 rows x 24 columns]

In [50]:
# append y_train into X_train to form a dataset and to handle the outliers
X_train['RainTomorrow'] = y_train

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [51]:
X_train

Location  MinTemp  MaxTemp  ...  Month  Day  RainTomorrow
89080          GoldCoast     18.3     19.8  ...      5   25           Yes
56495           Ballarat      7.6     25.1  ...     12    1            No
63581   MelbourneAirport      7.7     13.4  ...      5   26           Yes
21452      NorfolkIsland     15.5     20.3  ...      5   16            No
2498              Albury     18.1     32.8  ...      1   25            No
...                  ...      ...      ...  ...    ...  ...           ...
17553          Newcastle     25.1     40.7  ...      1   31            No
38527         WaggaWagga      8.8     16.0  ...      8   10            No
131812        Launceston      4.4     14.5  ...      7    7           Yes
1510              Albury      1.7     20.6  ...      5    3            No
119227             Perth      3.8     17.1  ...      9   28            No

[113754 rows x 25 columns]

In [52]:
Q1 = X_train.quantile(0.25)
Q3 = X_train.quantile(0.75)
IQR = Q3 - Q1
X_train_drop_outliers = X_train[~((X_train < (Q1 - 1.5*IQR)) | (X_train > (Q3 + 1.5*IQR))).any(axis=1)]
X_train_drop_outliers

Location  MinTemp  MaxTemp  ...  Month  Day  RainTomorrow
56495           Ballarat      7.6     25.1  ...     12    1            No
63581   MelbourneAirport      7.7     13.4  ...      5   26           Yes
2498              Albury     18.1     32.8  ...      1   25            No
49515        Tuggeranong      9.2     25.9  ...      1    7            No
1578              Albury      5.0     14.8  ...      7   13           Yes
...                  ...      ...      ...  ...    ...  ...           ...
94608           Adelaide     10.0     13.6  ...      8   19           Yes
14441              Moree      7.3     21.9  ...      9    6            No
37139         WaggaWagga     10.2     14.3  ...      8   23           Yes
131812        Launceston      4.4     14.5  ...      7    7           Yes
1510              Albury      1.7     20.6  ...      5    3            No

[87529 rows x 25 columns]

In [0]:
X_train = X_train_drop_outliers.drop(['RainTomorrow'], axis=1)
y_train = X_train_drop_outliers['RainTomorrow']

**Cross Validation on Training set**

In [56]:
accuracy = cross_val_score(clf,X_train,y_train,cv=10)
print('accuracy : ', accuracy)
print('mean : ', accuracy.mean())
print('std : ', accuracy.std())

accuracy :  [0.86918771 0.86884497 0.86713127 0.8694162  0.87421456 0.87170113
 0.86953045 0.86735976 0.8728436  0.87145795]
mean :  0.8701687588021532
std :  0.0021986105847968743


Note : The model is low bias and low variance

**Training and Test sets**

In [57]:
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('\n\nTraining and Test Sets result')
print('\naccuracy score : ', accuracy_score(y_test,y_pred))
print('\nconfusion matrix : \n', confusion_matrix(y_test, y_pred))
print('\nclassification report : \n', classification_report(y_test,y_pred))

print('Training set score : ',clf.score(X_train,y_train))
print('Test set score : ',clf.score(X_test,y_test))



Training and Test Sets result

accuracy score :  0.8340658954252963

confusion matrix : 
 [[20046  2075]
 [ 2644  3674]]

classification report : 
               precision    recall  f1-score   support

          No       0.88      0.91      0.89     22121
         Yes       0.64      0.58      0.61      6318

    accuracy                           0.83     28439
   macro avg       0.76      0.74      0.75     28439
weighted avg       0.83      0.83      0.83     28439

Training set score :  0.8707856824595277
Test set score :  0.8340658954252963


Note : Train and test scores are slightly different.  
The model is not overfitting.  
But let's try adding regularization.

In [63]:
# C=inverse regularization strength

# using the same preprocessor
model = LogisticRegression(solver='sag', max_iter=500, n_jobs = -1, C=0.01)
clf = Pipeline(steps=[
      ('preprocessor', preprocessor),
      ('model', model)
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('\n\nTraining and Test Sets result')
print('\naccuracy score : ', accuracy_score(y_test,y_pred))
print('\nconfusion matrix : \n', confusion_matrix(y_test, y_pred))
print('\nclassification report : \n', classification_report(y_test,y_pred))

print('Training set score : ',clf.score(X_train,y_train))
print('Test set score : ',clf.score(X_test,y_test))



Training and Test Sets result

accuracy score :  0.832905517071627

confusion matrix : 
 [[20363  1758]
 [ 2994  3324]]

classification report : 
               precision    recall  f1-score   support

          No       0.87      0.92      0.90     22121
         Yes       0.65      0.53      0.58      6318

    accuracy                           0.83     28439
   macro avg       0.76      0.72      0.74     28439
weighted avg       0.82      0.83      0.83     28439

Training set score :  0.865347484833598
Test set score :  0.832905517071627


Note : adding regularization makes the scores getting closer

# Trial 4
- cap the outliers in df
- impute the missing categorical values with mode
- impute the missing numerical values with median

In [64]:
df

Location  MinTemp  MaxTemp  Rainfall  ...  RainTomorrow  Year Month  Day
0        Albury     13.4     22.9       0.6  ...            No  2008    12    1
1        Albury      7.4     25.1       0.0  ...            No  2008    12    2
2        Albury     12.9     25.7       0.0  ...            No  2008    12    3
3        Albury      9.2     28.0       0.0  ...            No  2008    12    4
4        Albury     17.5     32.3       1.0  ...            No  2008    12    5
...         ...      ...      ...       ...  ...           ...   ...   ...  ...
142188    Uluru      3.5     21.8       0.0  ...            No  2017     6   20
142189    Uluru      2.8     23.4       0.0  ...            No  2017     6   21
142190    Uluru      3.6     25.3       0.0  ...            No  2017     6   22
142191    Uluru      5.4     26.9       0.0  ...            No  2017     6   23
142192    Uluru      7.8     27.0       0.0  ...            No  2017     6   24

[142193 rows x 25 columns]

In [0]:
# cap the outliers
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
lower_cap = Q1 - 1.5*IQR
upper_cap = Q3 + 1.5*IQR

features = lower_cap.index.values

for feature in features :
  df[feature] = np.where(df[feature]<lower_cap[feature],lower_cap[feature], df[feature])
  df[feature] = np.where(df[feature]>upper_cap[feature],upper_cap[feature], df[feature])

In [107]:
df.shape

(142193, 25)

In [108]:
df_drop_outliers = df[~((df < (Q1 - 1.5*IQR)) | (df > (Q3 + 1.5*IQR))).any(axis=1)]
df_drop_outliers.shape

(142193, 25)

Note : no outliers are dropped, cap outliers successfully

In [109]:
df

Location  MinTemp  MaxTemp  Rainfall  ...  RainTomorrow    Year Month   Day
0        Albury     13.4     22.9       0.6  ...            No  2008.0  12.0   1.0
1        Albury      7.4     25.1       0.0  ...            No  2008.0  12.0   2.0
2        Albury     12.9     25.7       0.0  ...            No  2008.0  12.0   3.0
3        Albury      9.2     28.0       0.0  ...            No  2008.0  12.0   4.0
4        Albury     17.5     32.3       1.0  ...            No  2008.0  12.0   5.0
...         ...      ...      ...       ...  ...           ...     ...   ...   ...
142188    Uluru      3.5     21.8       0.0  ...            No  2017.0   6.0  20.0
142189    Uluru      2.8     23.4       0.0  ...            No  2017.0   6.0  21.0
142190    Uluru      3.6     25.3       0.0  ...            No  2017.0   6.0  22.0
142191    Uluru      5.4     26.9       0.0  ...            No  2017.0   6.0  23.0
142192    Uluru      7.8     27.0       0.0  ...            No  2017.0   6.0  24.0

[142193 rows x 25 columns]

In [0]:
X = df.drop(['RainTomorrow'], axis=1)
y = df['RainTomorrow']

**Cross Validation**

In [111]:
accuracy = cross_val_score(clf,X,y,cv=10)
print('accuracy : ', accuracy)
print('mean : ', accuracy.mean())
print('std : ', accuracy.std())

accuracy :  [0.83185654 0.78769339 0.83410689 0.81876363 0.83001618 0.83128209
 0.77108095 0.81630213 0.82108446 0.84190168]
mean :  0.8184087934677446
std :  0.02115354600608366


Note :  low bias and low variance.  
The result is better than keeping or dropping the outliers in df

**Training and Test Sets**

In [112]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('\n\nTraining and Test Sets result')
print('\naccuracy score : ', accuracy_score(y_test,y_pred))
print('\nconfusion matrix : \n', confusion_matrix(y_test, y_pred))
print('\nclassification report : \n', classification_report(y_test,y_pred))

print('\nTraining set score : ',clf.score(X_train,y_train))
print('Test set score : ',clf.score(X_test,y_test))



Training and Test Sets result

accuracy score :  0.8426456626463659

confusion matrix : 
 [[21002  1067]
 [ 3408  2962]]

classification report : 
               precision    recall  f1-score   support

          No       0.86      0.95      0.90     22069
         Yes       0.74      0.46      0.57      6370

    accuracy                           0.84     28439
   macro avg       0.80      0.71      0.74     28439
weighted avg       0.83      0.84      0.83     28439


Training set score :  0.8439615310230849
Test set score :  0.8426456626463659


Note : the model is not overfitting

# Trial 5
- cap the outliers in X_train
- cap the outliers in X_test using the upper_cap and lower_cap of X_train
- impute the missing categorical values with mode
- impute the missing numerical values with median

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/WoradeeKongthong/raining_tomorrow_classification/master/weatherAUS.csv')

In [0]:
# drop RISK_MM column (Recommendation from data description in Kaggle)
df.drop(['RISK_MM'], axis = 1, inplace = True)

# Extract Year, Month, Day from Date column
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

# drop Date column
df.drop(['Date'], axis = 1, inplace = True)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Location       142193 non-null  object 
 1   MinTemp        141556 non-null  float64
 2   MaxTemp        141871 non-null  float64
 3   Rainfall       140787 non-null  float64
 4   Evaporation    81350 non-null   float64
 5   Sunshine       74377 non-null   float64
 6   WindGustDir    132863 non-null  object 
 7   WindGustSpeed  132923 non-null  float64
 8   WindDir9am     132180 non-null  object 
 9   WindDir3pm     138415 non-null  object 
 10  WindSpeed9am   140845 non-null  float64
 11  WindSpeed3pm   139563 non-null  float64
 12  Humidity9am    140419 non-null  float64
 13  Humidity3pm    138583 non-null  float64
 14  Pressure9am    128179 non-null  float64
 15  Pressure3pm    128212 non-null  float64
 16  Cloud9am       88536 non-null   float64
 17  Cloud3pm       85099 non-null

In [0]:
X = df.drop(['RainTomorrow'], axis=1)
y = df['RainTomorrow']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [120]:
# append y_train into X_train to form a dataset and to handle the outliers
X_train['RainTomorrow'] = y_train

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [121]:
X_train

Location  MinTemp  MaxTemp  Rainfall  ...  Year  Month Day  RainTomorrow
118889         Perth     15.5     20.9       0.2  ...  2011     10  26           Yes
124806       Walpole     13.3     27.8       0.0  ...  2011     11   2            No
100839     Nuriootpa      0.3     12.0       0.0  ...  2011      6  14            No
134988  AliceSprings     22.6     31.7       0.0  ...  2014     11  27            No
138997        Darwin     24.6     34.4       0.0  ...  2017      3   1            No
...              ...      ...      ...       ...  ...   ...    ...  ..           ...
31642         Sydney     16.1     29.7       0.2  ...  2014      3  18            No
90808      GoldCoast     16.2     21.9      21.6  ...  2017      6  11           Yes
114472    PearceRAAF     11.4     24.6       0.0  ...  2016     11   7            No
36090     WaggaWagga      5.6     14.5       0.0  ...  2009      9   9            No
126686        Hobart      6.5     13.0       0.0  ...  2008      7  13            No

[113754 rows x 25 columns]

In [122]:
Q1 = X_train.quantile(0.25)
Q3 = X_train.quantile(0.75)
IQR = Q3 - Q1

lower_cap = Q1 - 1.5*IQR
upper_cap = Q3 + 1.5*IQR

features = lower_cap.index.values

for feature in features :
  X_train[feature] = np.where(X_train[feature]<lower_cap[feature],lower_cap[feature], X_train[feature])
  X_train[feature] = np.where(X_train[feature]>upper_cap[feature],upper_cap[feature], X_train[feature])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [123]:
X_train.shape

(113754, 25)

In [124]:
X_train_drop_outliers = X_train[~((X_train < (Q1 - 1.5*IQR)) | (X_train > (Q3 + 1.5*IQR))).any(axis=1)]
X_train_drop_outliers.shape

(113754, 25)

Note : no outliers are dropped, cap successfully

In [0]:
# get y_train from X_train
X_train = X_train_drop_outliers.drop(['RainTomorrow'], axis=1)
y_train = X_train_drop_outliers['RainTomorrow']

**Cross Validation on Training set**

In [128]:
accuracy = cross_val_score(clf,X_train,y_train,cv=10)
print('accuracy : ', accuracy)
print('mean : ', accuracy.mean())
print('std : ', accuracy.std())

accuracy :  [0.84379395 0.84045359 0.84194796 0.84502461 0.84483516 0.84043956
 0.84615385 0.84052747 0.84131868 0.84483516]
mean :  0.8429330002627472
std :  0.002108412164477752


Note : low bias and low variance 

**Training and Test sets**

In [130]:
# first, cap the outliers in Tes set 

for feature in features :
  X_test[feature] = np.where(X_test[feature]<lower_cap[feature],lower_cap[feature], X_test[feature])
  X_test[feature] = np.where(X_test[feature]>upper_cap[feature],upper_cap[feature], X_test[feature])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [131]:
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print('\n\nTraining and Test Sets result')
print('\naccuracy score : ', accuracy_score(y_test,y_pred))
print('\nconfusion matrix : \n', confusion_matrix(y_test, y_pred))
print('\nclassification report : \n', classification_report(y_test,y_pred))

print('Training set score : ',clf.score(X_train,y_train))
print('Test set score : ',clf.score(X_test,y_test))



Training and Test Sets result

accuracy score :  0.8425050107247091

confusion matrix : 
 [[20970  1041]
 [ 3438  2990]]

classification report : 
               precision    recall  f1-score   support

          No       0.86      0.95      0.90     22011
         Yes       0.74      0.47      0.57      6428

    accuracy                           0.84     28439
   macro avg       0.80      0.71      0.74     28439
weighted avg       0.83      0.84      0.83     28439

Training set score :  0.8440230673207096
Test set score :  0.8425050107247091


Note : There is no overfitting.
The training and test score are closer than dropping the outliers from X_train.